server:
  port: 7070

# Para conectar con el Eureka Server (Sevice Discovery)
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7076/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:            
        - id: microservicio-product
          # lb(Load Banlacing) - MICROSERVICIO-PRODUCT(Nombre de la aplicaci贸n - se registr贸 en EUREKA)
          uri: lb://microservicio-product
          predicates:
            - Path=/api/1.0.0/products/**
        - id: microservicio-producttypes
          # lb(Load Banlacing) - MICROSERVICIO-PRODUCT(Nombre de la aplicaci贸n - se registr贸 en EUREKA)
          uri: lb://microservicio-producttypes
          predicates:
            - Path=/api/1.0.0/producttypes/**
        